### ISSUE TITLE
Warning: Image is too big to fit on screen

### ISSUE THREAD

**Issue by xiaonansun** [talmo/leap#12]
Hi Talmo,
I am trying to create a skeleton on my data but there seems to be an error possibly associated with the dimensions of the video. The dimensions are certainly divisible by 4 but it's non-square. The error I am getting is `Warning: Image is too big to fit on screen; displaying at 200%` after pressing the "Import from workspace" button in the **Create skeleton** GUI window, generating a new "Select default body part positions" window which is blank. Do I need to downsample my video? 

Thank you for your help.

Best,

Richard

![image](https://user-images.githubusercontent.com/42507167/50229796-2351cb80-0379-11e9-8e8a-88e7d07f8c0e.png)

![image](https://user-images.githubusercontent.com/42507167/50229810-2baa0680-0379-11e9-9b8d-b13ddd41fabc.png)

**Comment by xiaonansun** [comment]
also, this is the `h5disp` for this video:
`    Dataset 'box' 
        Size:  512x640x1x275
        MaxSize:  512x640x1x275
        Datatype:   H5T_IEEE_F64LE (double)
        ChunkSize:  512x640x1x1
        Filters:  deflate(1)
        FillValue:  0.000000
        Attributes:
            'dtype':  'double'
    Dataset 'dataIdx' 
        Size:  275x1
        MaxSize:  275x1
        Datatype:   H5T_IEEE_F64LE (double)
        ChunkSize:  []
        Filters:  none
        FillValue:  0.000000
        Attributes:
            'dtype':  'double'
    Dataset 'exptID' 
        Size:  275x1
        MaxSize:  275x1
        Datatype:   H5T_IEEE_F64LE (double)
        ChunkSize:  []
        Filters:  none
        FillValue:  0.000000
        Attributes:
            'dtype':  'double'
    Group '/clusters' 
        Dataset 'G' 
            Size:  275x1
            MaxSize:  275x1
            Datatype:   H5T_IEEE_F64LE (double)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'double'
        Dataset 'cluster_centroids' 
            Size:  512x640x1x5
            MaxSize:  512x640x1x5
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'k' 
            Size:  1x1
            MaxSize:  1x1
            Datatype:   H5T_IEEE_F64LE (double)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'double'
    Group '/pca' 
        Dataset 'coeff' 
            Size:  327680x100
            MaxSize:  327680x100
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'coeff_box' 
            Size:  512x640x1x100
            MaxSize:  512x640x1x100
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'explained' 
            Size:  2159x1
            MaxSize:  2159x1
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'latent' 
            Size:  2159x1
            MaxSize:  2159x1
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'mu' 
            Size:  1x327680
            MaxSize:  1x327680
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'score' 
            Size:  275x100
            MaxSize:  275x100
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'
        Dataset 'tsquared' 
            Size:  2160x1
            MaxSize:  2160x1
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
            Attributes:
                'dtype':  'single'`

**Comment by talmo** [comment]
Hey Richard,

I think the image is showing up as white because it's a `double`. This is because if the image is a floating point type (`single`/`double`), then the expected range of values is in [0, 1] and you probably still have them in the `uint8` range of [0, 255] and MATLAB just displays it as all white.

I'd definitely recommend saving out the movie as `uint8` if possible -- it'll be way smaller in filesize and it gets auto-converted when loaded into LEAP anyway.

If you need to have floating-point precision, I'd recommend saving it as a `single` (== `float32`) which GPUs are much more optimized for than `double` (== `float64`) precision.

Regarding the size: I'd definitely resize it down to 256x320 if I were you, at least for the first tests. You might also need to decrease the batch size to make sure you have enough GPU memory and increase the sigma (~8 is probably good) to account for the larger scale of the features.

Give it a go and let me know if you have any issues!

Talmo

**Comment by xiaonansun** [comment]
Thank you for the quick response Talmo. I'll give it a go and let you know.
Best,
Richard

**Comment by talmo** [comment]
Hey Richard,

Sorry about that, I think you might need to define the edges to get the visualization working. You can do this by filling in the "parent" column with the name of the other joints, e.g., "head" for the earR or earL.

**Comment by xiaonansun** [comment]
Got it. Thank you!
