### ISSUE TITLE
Strange new error

### ISSUE THREAD

**Issue by kbakhurin** [talmo/leap#15]
Hi Talmo,

Suddenly encountering a new problem with LEAP. 

during the cluster_samples program, the PCA computation step results in 90% of the variance explained in *blank* modes, where there are 0 modes. The matlab command prompt reads:

Warning: Columns of X are linearly dependent to within machine precision.
Using only the first 0 components to compute TSQUARED.

Do you know what this could be caused by? I tried it with two different videos.  I feel like I remember seeing this happen before but I can't remember exactly what where the circumstances.

Thanks!

**Comment by kbakhurin** [comment]
Hi Talmo,

Here is a screenshot of the cluster sampling window after i load samples and compute PCA.

![image](https://user-images.githubusercontent.com/32279784/51805354-39855e00-223a-11e9-89da-47f2e4d74036.png)

**Comment by talmo** [comment]
Hey Konstantin,

Very bizarre error. I can't see anything in the code that would be an obvious reason why this is happening.

Try just skipping the PCA Preprocessing and just cluster without it -- it should still work, and if not it'll at least suggest a reason as to what's wrong.
