### ISSUE TITLE
no predictions created

### ISSUE THREAD

**Issue by WeissShahaf** [talmo/leap#29]
Hi,
i managed to install sleap, label,train. when visualizing during training and validation i can see good labeling, but no predictions are created. the output simple says predicted "0" frames successfully.

if run inference. it says all frames were predicted. but no new labels are created.

this was ran using linux and python.

the python version is much easier to work with, but looks like it's doing something else than the MATLAB version with the PCA and clustering. it also accepts non .h5 movies.

is there a difference between the matlab/python versions? which is the updated one?

I tried installing using matlab and git , and also the conda installation of SLEAP. both have the same issue. it seems to stem from tensor flow issues, as far as i can understand.

what are the current supported TF and cuda versions ?

**Comment by talmo** [comment]
Hi @WeissShahaf,

I'd recommend you check out the successor of LEAP -- SLEAP, available at https://sleap.ai and https://github.com/murthylab/sleap.

You'll be able to do everything you could with LEAP and more.

Cheers!
