### ISSUE TITLE
Error using cluster_sample/LoadsamplesButtonPushed (line 267)

### ISSUE THREAD

**Issue by ElectricSquirrel** [talmo/leap#4]
> In parallel.internal.pool.deserialize (line 9)
  In parallel.internal.pool.deserializeFunction (line 12)
  In remoteParallelFunction (line 33)
Error using cluster_sample/LoadsamplesButtonPushed (line 267)
While setting property 'Enable' of class 'Label':
Value must be specified as the string 'on' or 'off'

Error in appdesigner.internal.service.AppManagementService/tryCallback (line 207)
                    callback(app, event);

Error in matlab.apps.AppBase>@(source,event)tryCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 262)
Error while evaluating Button PrivateButtonPushedFcn

**Comment by talmo** [comment]
Hi @ElectricSquirrel,

This should be working in MATLAB R2018a, but I've just pushed a fix for this issue (897b5ec6a36fed7a63f4c8e3713f1b43b5c786e2) for older versions.

You can `git pull` to update the repo or just re-download the latest [`cluster_sample.mlapp`](https://github.com/talmo/leap/blob/master/leap/guis/cluster_sample.mlapp) and see if it fixes your problem.

Let me know if you have any more problems! (and let me know what version of MATLAB you're on)

Talmo
